/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/features/{timeframe}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Features
         * @description Indicadores de um ativo, do mais recente para o mais antigo.
         *
         *     Timeframes: 15m, 1h, 1d — "24h" é aceito como sinônimo de "1d"
         *     (grafia histórica da tabela features_24h).
         */
        get: operations["list_features_api_v1_features__timeframe__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/klines/{timeframe}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Klines
         * @description Candles de um ativo, do mais recente para o mais antigo. Timeframes: 15m, 1h, 1d.
         */
        get: operations["list_klines_api_v1_klines__timeframe__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Preferences
         * @description Preferências do usuário autenticado.
         *
         *     Um usuário que nunca salvou nada recebe os valores padrão (200, não 404),
         *     para o app abrir sem tratamento especial na primeira visita. O e-mail é
         *     somente leitura e vem do token do Supabase, não do Firestore.
         */
        get: operations["get_preferences_api_v1_preferences_get"];
        /**
         * Save Preferences
         * @description Substitui as preferências do usuário autenticado.
         *
         *     Idempotente: reenviar o mesmo payload produz o mesmo documento. O dono do
         *     documento vem sempre do token — `user_id` ou `email` no corpo são
         *     rejeitados com 422.
         */
        put: operations["save_preferences_api_v1_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Symbols
         * @description Ativos rastreados pela plataforma, em ordem alfabética.
         */
        get: operations["list_symbols_api_v1_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickers/24h": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List 24H Snapshots
         * @description Snapshot 24h mais recente por ativo (ou de um ativo específico).
         */
        get: operations["list_24h_snapshots_api_v1_tickers_24h_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChartSettings
         * @description Chart rendering preferences (accessibility).
         */
        ChartSettings: {
            /**
             * Hollow Up Candles
             * @default false
             */
            hollow_up_candles: boolean;
        };
        /**
         * FeatureRowOut
         * @description One indicator row from features_{15m,1h,24h}.
         *
         *     Field names mirror the output columns produced by
         *     app/feature_engineering/config/features.yml (macd, macd_histogram
         *     and bb_width are Postgres GENERATED columns). Indicators are
         *     nullable: warm-up windows legitimately produce NULLs.
         */
        FeatureRowOut: {
            /** Atr 14 */
            atr_14?: number | null;
            /** Avg Price Deviation Sma20 */
            avg_price_deviation_sma20?: number | null;
            /** Avg Price Deviation Sma50 */
            avg_price_deviation_sma50?: number | null;
            /** Avg Price Deviation Sma200 */
            avg_price_deviation_sma200?: number | null;
            /** Bb Lower */
            bb_lower?: number | null;
            /** Bb Middle */
            bb_middle?: number | null;
            /** Bb Upper */
            bb_upper?: number | null;
            /** Bb Width */
            bb_width?: number | null;
            /** Bid Ask Spread */
            bid_ask_spread?: number | null;
            /** Ema 12 */
            ema_12?: number | null;
            /** Ema 26 */
            ema_26?: number | null;
            /** Macd */
            macd?: number | null;
            /** Macd Histogram */
            macd_histogram?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            /** Order Imbalance */
            order_imbalance?: number | null;
            /** Price Change Percent */
            price_change_percent?: number | null;
            /** Rsi 14 */
            rsi_14?: number | null;
            /** Sma 20 */
            sma_20?: number | null;
            /** Sma 50 */
            sma_50?: number | null;
            /** Sma 200 */
            sma_200?: number | null;
            /** Symbol */
            symbol: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Volume Change 24H */
            volume_change_24h?: number | null;
            /** Volume Sma 20 */
            volume_sma_20?: number | null;
        };
        /**
         * HealthOut
         * @description Service liveness response.
         */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KlineOut
         * @description One candlestick row from klines_{15m,1h,1d}.
         */
        KlineOut: {
            /** Close */
            close: number;
            /** Close Time */
            close_time?: string | null;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Number Of Trades */
            number_of_trades?: number | null;
            /** Open */
            open: number;
            /**
             * Open Time
             * Format: date-time
             */
            open_time: string;
            /** Quote Asset Volume */
            quote_asset_volume?: number | null;
            /** Symbol */
            symbol: string;
            /** Taker Buy Base Asset Volume */
            taker_buy_base_asset_volume?: number | null;
            /** Taker Buy Quote Asset Volume */
            taker_buy_quote_asset_volume?: number | null;
            /** Volume */
            volume: number;
        };
        /**
         * NotificationSettings
         * @description Digest switch, delivery channel and selected topics.
         */
        NotificationSettings: {
            /**
             * Channel
             * @default email
             * @enum {string}
             */
            channel: "email" | "sms" | "whatsapp";
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            topics?: components["schemas"]["NotificationTopics"];
        };
        /**
         * NotificationTopics
         * @description Which daily digest topics the user opted into.
         */
        NotificationTopics: {
            /**
             * Forecast Gap
             * @default false
             */
            forecast_gap: boolean;
            /**
             * Model Runs
             * @default false
             */
            model_runs: boolean;
            /**
             * Volatility
             * @default false
             */
            volatility: boolean;
            /**
             * Volume Movers
             * @default false
             */
            volume_movers: boolean;
        };
        /**
         * PreferencesIn
         * @description Payload accepted when saving preferences.
         *
         *     ``extra="forbid"`` is deliberate: it rejects any attempt to smuggle
         *     ``user_id`` or ``email`` into the document. The owner of the document
         *     always comes from the validated token, never from the request body.
         */
        PreferencesIn: {
            chart?: components["schemas"]["ChartSettings"];
            /** Display Name */
            display_name?: string | null;
            notifications?: components["schemas"]["NotificationSettings"];
            /** Phone */
            phone?: string | null;
        };
        /**
         * PreferencesOut
         * @description Preferences returned to the client.
         *
         *     ``extra="ignore"`` (not ``forbid``): documents written by an older
         *     schema version must never break a read.
         */
        PreferencesOut: {
            chart?: components["schemas"]["ChartSettings"];
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            notifications?: components["schemas"]["NotificationSettings"];
            /** Phone */
            phone?: string | null;
        };
        /**
         * SymbolOut
         * @description One tracked symbol from the symbols reference table.
         */
        SymbolOut: {
            /** Created At */
            created_at?: string | null;
            /** Symbol */
            symbol: string;
        };
        /**
         * Ticker24hOut
         * @description Latest 24-hour market snapshot from ticker_24hr_history.
         */
        Ticker24hOut: {
            /** Ask Price */
            ask_price?: number | null;
            /** Bid Price */
            bid_price?: number | null;
            /** Close Time */
            close_time?: string | null;
            /** Count */
            count?: number | null;
            /** High Price */
            high_price?: number | null;
            /** Last Price */
            last_price?: number | null;
            /** Low Price */
            low_price?: number | null;
            /** Open Price */
            open_price?: number | null;
            /**
             * Open Time
             * Format: date-time
             */
            open_time: string;
            /** Price Change */
            price_change?: number | null;
            /** Price Change Percent */
            price_change_percent?: number | null;
            /** Quote Volume */
            quote_volume?: number | null;
            /** Symbol */
            symbol: string;
            /** Volume */
            volume?: number | null;
            /** Weighted Avg Price */
            weighted_avg_price?: number | null;
        };
        /**
         * Timeframe
         * @description A market-data timeframe and everything derived from it.
         *
         *     Canonical values are the kline spellings ("15m", "1h", "1d");
         *     "24h" is accepted as an alias for D1 because the feature tables
         *     use that historical name (features_24h).
         * @enum {string}
         */
        Timeframe: "15m" | "1h" | "1d";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_features_api_v1_features__timeframe__get: {
        parameters: {
            query: {
                /** @description ISO 8601, inclusivo */
                end?: string | null;
                limit?: number;
                /** @description ISO 8601, inclusivo */
                start?: string | null;
                /** @description ex.: BTCUSDT */
                symbol: string;
            };
            header?: never;
            path: {
                timeframe: components["schemas"]["Timeframe"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_klines_api_v1_klines__timeframe__get: {
        parameters: {
            query: {
                /** @description ISO 8601, inclusivo */
                end?: string | null;
                limit?: number;
                /** @description ISO 8601, inclusivo */
                start?: string | null;
                /** @description ex.: BTCUSDT */
                symbol: string;
            };
            header?: never;
            path: {
                timeframe: components["schemas"]["Timeframe"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KlineOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_api_v1_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
        };
    };
    save_preferences_api_v1_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_symbols_api_v1_symbols_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolOut"][];
                };
            };
        };
    };
    list_24h_snapshots_api_v1_tickers_24h_get: {
        parameters: {
            query?: {
                /** @description ex.: BTCUSDT */
                symbol?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticker24hOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
