"""Daily market reading generated by an LLM (OpenCode Zen → OpenRouter fallback).

Honesty rules (Design.md §6): the model only rewrites numbers we computed
here — it never receives permission to invent data. The reading is global
(same for every user) and cached per UTC day: Firestore is the durable
cache, a process dict avoids re-reading it on every request, and a lock
makes generation single-flight under concurrency.

Só texto aprovado pelo portão ``_is_valid_reading`` chega ao cache: com
modelos de raciocínio, uma resposta truncada ou o próprio raciocínio vazado
ficariam presos no Firestore até virar o dia UTC.
"""

import logging
import re
import threading
from datetime import datetime, timezone
from typing import Optional

from app.clients.firebase import get_firestore
from app.clients.llm_gateway import GatewayAttempt, LlmGatewayClient, LlmGatewayError
from app.core.timeframe import Timeframe
from app.repositories.features_repository import FeaturesRepository
from app.repositories.tickers_repository import TickersRepository
from app.schemas.insights import DailyReadingOut
from config import Settings, get_settings

logger = logging.getLogger(__name__)

DISCLAIMER = "Leia as previsões como cenários, não como recomendação de compra ou venda."

# Estilo definido com o usuário (2026-08-22): clareza acima de tudo.
# 2026-08-26: os modelos passaram a escrever números por extenso ("oito
# vírgula sessenta e sete por cento"), o que trava a leitura; a regra dos
# algarismos é explícita e com exemplo porque a proibição de hífens e
# símbolos estava empurrando o modelo para o extenso.
SYSTEM_PROMPT = (
    "Você escreve a leitura diária de um painel de análise de criptomoedas, em português do Brasil. "
    "Regras obrigatórias: não use hífens nem travessões como pontuação; não use emojis; não use listas, "
    "escreva um único parágrafo corrido de no máximo cinco frases. Foque em clareza: traduza os números "
    "recebidos em conhecimento rápido, dizendo o que eles significam para quem acompanha o mercado. "
    "Use apenas os números fornecidos na mensagem do usuário, exatamente como fornecidos. É proibido "
    "inventar, extrapolar ou arredondar dados que não estejam na mensagem. "
    "Escreva todo número em algarismos, nunca por extenso: escreva 8,67% e não oito vírgula sessenta "
    "e sete por cento; escreva 38.407.882 USDT e não trinta e oito milhões. Use o símbolo % para "
    "porcentagens e vírgula como separador decimal. Não recomende compra nem venda. "
    "Não inclua avisos legais, o painel já os exibe. Não cumprimente nem se despeça, entregue só a leitura."
)

_INSUFFICIENT_DATA_THRESHOLD = 5

# Portão de validação do texto gerado. Os modelos da cadeia são de raciocínio:
# quando o orçamento acaba pensando, o que sobra é raciocínio em inglês, longo
# e cortado no meio. Nada disso pode virar leitura do dia nem entrar no cache.
_MAX_READING_CHARS = 900
_MAX_READING_SENTENCES = 6
# Fim de frase = pontuação seguida de espaço ou fim do texto. O ponto de
# milhar ("38.407.882") vem colado em dígito e não conta como frase.
_SENTENCE_END = re.compile(r"[.!?…]+(?=\s|$)")
# Marcadores de raciocínio em inglês (o prompt pede pt-BR; o modelo pensa em inglês).
_ENGLISH_MARKERS = (
    "we need",
    "we should",
    "we must",
    "let's",
    "lets ",
    "the user",
    "i should",
    "i need",
    "okay,",
    "the assistant",
)
# Palavras funcionais que qualquer parágrafo em pt-BR carrega.
_PT_MARKERS = (
    " de ",
    " da ",
    " do ",
    " das ",
    " dos ",
    " que ",
    " para ",
    " com ",
    " não ",
    " uma ",
    " nas ",
    " nos ",
    " em ",
    " e ",
)
_ACCENTS = "áàâãéêíóôõúüç"


def _looks_english(text: str) -> bool:
    """Heurística simples: raciocínio em inglês nunca parece um parágrafo pt-BR."""
    lowered = f" {text.lower()} "
    if any(marker in lowered for marker in _ENGLISH_MARKERS):
        return True
    pt_hits = sum(1 for marker in _PT_MARKERS if marker in lowered)
    has_accent = any(char in lowered for char in _ACCENTS)
    return pt_hits < 2 and not has_accent


def _rejection_reason(text: str) -> Optional[str]:
    """Motivo pelo qual o texto não serve como leitura, ou None quando serve."""
    stripped = text.strip()
    if not stripped:
        return "texto vazio"
    if "<think" in stripped.lower():
        return "raciocínio vazado (<think>)"
    if len(stripped) > _MAX_READING_CHARS:
        return f"{len(stripped)} caracteres (máximo {_MAX_READING_CHARS})"
    sentences = [part for part in _SENTENCE_END.split(stripped) if part.strip()]
    if len(sentences) > _MAX_READING_SENTENCES:
        return f"{len(sentences)} frases (máximo {_MAX_READING_SENTENCES})"
    if _looks_english(stripped):
        return "texto em inglês"
    return None


def _is_valid_reading(text: str) -> bool:
    """True quando o texto serve como leitura do dia (pt-BR, curta, sem raciocínio)."""
    reason = _rejection_reason(text)
    if reason:
        logger.warning("Leitura rejeitada pelo validador: %s. Início: %.80r", reason, text)
        return False
    return True


class InsightsUnavailableError(RuntimeError):
    """No cached reading and generation is impossible right now."""


_cache: dict[str, DailyReadingOut] = {}
_lock = threading.Lock()


def _today_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _fmt(value: object, decimals: int = 2) -> str:
    """Número no formato pt-BR (vírgula decimal, ponto de milhar).

    O prompt manda copiar os números "exatamente como fornecidos", então o
    contexto já chega na forma em que deve aparecer na tela.
    """
    if not isinstance(value, (int, float)):
        return "sem dado"
    return f"{value:,.{decimals}f}".replace(",", "\0").replace(".", ",").replace("\0", ".")


def build_attempts(settings: Settings) -> list[GatewayAttempt]:
    """Fallback chain in priority order; gateways without a key are skipped."""
    attempts: list[GatewayAttempt] = []
    if settings.OPENCODE_ZEN_API_KEY:
        for model in (settings.OPENCODE_ZEN_MODEL, settings.OPENCODE_ZEN_FALLBACK_MODEL):
            if model:
                attempts.append(
                    GatewayAttempt(
                        provider="opencode-zen",
                        api_key=settings.OPENCODE_ZEN_API_KEY,
                        model=model,
                    )
                )
    if settings.OPENROUTER_API_KEY and settings.OPENROUTER_MODEL:
        attempts.append(
            GatewayAttempt(
                provider="openrouter",
                api_key=settings.OPENROUTER_API_KEY,
                model=settings.OPENROUTER_MODEL,
            )
        )
    return attempts


class InsightsService:
    """Builds the numeric context, runs the LLM fallback chain and caches the reading."""

    def __init__(
        self,
        tickers_repo: TickersRepository,
        features_repo: FeaturesRepository,
        client: Optional[LlmGatewayClient] = None,
        firestore_client=None,
    ) -> None:
        self.tickers_repo = tickers_repo
        self.features_repo = features_repo
        self.client = client or LlmGatewayClient()
        self._firestore = firestore_client

    # -- contexto ---------------------------------------------------------

    def build_context(self) -> str:
        """Aggregate the day's snapshot into a compact numeric brief (pt-BR)."""
        snapshots = self.tickers_repo.get_latest_24h_snapshots()
        rows = [s for s in snapshots if isinstance(s.get("price_change_percent"), (int, float))]
        if len(rows) < _INSUFFICIENT_DATA_THRESHOLD:
            raise InsightsUnavailableError("not enough market data to summarize")

        ups = sum(1 for s in rows if s["price_change_percent"] > 0)
        movers = sorted(rows, key=lambda s: abs(s["price_change_percent"]), reverse=True)[:3]
        volumes = sorted(
            (s for s in rows if isinstance(s.get("quote_volume"), (int, float))),
            key=lambda s: s["quote_volume"],
            reverse=True,
        )[:3]

        atr_lines: list[str] = []
        for snapshot in rows:
            last_price = snapshot.get("last_price")
            if not isinstance(last_price, (int, float)) or last_price <= 0:
                continue
            try:
                features = self.features_repo.query_features(
                    Timeframe.D1, snapshot["symbol"], limit=1
                )
            except Exception:  # noqa: BLE001 - um ativo sem features não derruba a leitura
                continue
            atr = features[0].get("atr_14") if features else None
            if isinstance(atr, (int, float)):
                atr_lines.append((snapshot["symbol"], atr / last_price * 100))
        atr_lines.sort(key=lambda pair: pair[1], reverse=True)

        parts = [
            f"Ativos acompanhados: {len(rows)}. Subiram nas últimas 24 horas: {ups}. "
            f"Caíram: {len(rows) - ups}.",
            "Maiores variações de preço em 24 horas: "
            + "; ".join(f"{s['symbol']} {_fmt(s['price_change_percent'])}%" for s in movers)
            + ".",
        ]
        if volumes:
            parts.append(
                "Maiores volumes em 24 horas (USDT): "
                + "; ".join(f"{s['symbol']} {_fmt(s['quote_volume'], 0)}" for s in volumes)
                + "."
            )
        if atr_lines:
            parts.append(
                "Maior volatilidade (ATR 14 relativo ao preço): "
                + "; ".join(f"{sym} {_fmt(v)}%" for sym, v in atr_lines[:3])
                + "."
            )
        return " ".join(parts)

    # -- cache ------------------------------------------------------------

    def _collection(self):
        client = self._firestore or get_firestore()
        return client.collection(get_settings().DAILY_READINGS_COLLECTION)

    def _read_stored(self, day: str) -> Optional[DailyReadingOut]:
        try:
            snapshot = self._collection().document(day).get()
        except Exception:  # noqa: BLE001 - Firestore fora do ar não impede gerar de novo
            logger.exception("Falha ao ler a leitura do dia %s no Firestore.", day)
            return None
        if not snapshot.exists:
            return None
        try:
            return DailyReadingOut.model_validate(snapshot.to_dict())
        except Exception:  # noqa: BLE001 - documento de versão antiga não derruba a rota
            logger.exception("Leitura do dia %s com formato inesperado.", day)
            return None

    def _store(self, reading: DailyReadingOut) -> None:
        try:
            self._collection().document(reading.date).set(reading.model_dump(mode="json"))
        except Exception:  # noqa: BLE001 - cache durável é acessório
            logger.exception("Falha ao gravar a leitura do dia %s no Firestore.", reading.date)

    # -- API --------------------------------------------------------------

    def get_daily_reading(self) -> DailyReadingOut:
        """Today's reading: process cache → Firestore → generate (single-flight).

        Raises:
            InsightsUnavailableError: Generation failed and there is no cached
                reading for today (the controller maps it to 503).
        """
        day = _today_utc()
        cached = _cache.get(day)
        if cached:
            return cached

        with _lock:
            cached = _cache.get(day)
            if cached:
                return cached

            stored = self._read_stored(day)
            if stored:
                _cache[day] = stored
                return stored

            attempts = build_attempts(get_settings())
            context = self.build_context()
            try:
                text, model = self.client.complete(
                    attempts,
                    system=SYSTEM_PROMPT,
                    user=(
                        "Escreva a leitura do dia com base apenas nestes números do último "
                        f"snapshot diário: {context}"
                    ),
                    validator=_is_valid_reading,
                )
            except LlmGatewayError as exc:
                raise InsightsUnavailableError(str(exc)) from exc

            reading = DailyReadingOut(
                date=day,
                generated_at=datetime.now(timezone.utc),
                model=model,
                text=text,
                disclaimer=DISCLAIMER,
            )
            self._store(reading)
            _cache[day] = reading
            return reading
